### ISSUE TITLE
Web data extraction on windows 10

### ISSUE THREAD

**Issue by adnanPBI** [ahmed-alnassif/net-spider#1]
Hello,
I had applied your tool in windows 10 using git clone and provided web address to extract but did not find any help, as below:

(venv) C:\Users\1TB\AppData\Local\Programs\Python\Python311\net-spider>python main.py -u [https://www.hangiev.com]
←[1;37m[←[34m11:25:47←[37m]←[0m←[1m←[37m[←[34mLOG←[37m]←[0m←[37m Starting porgram ...←[0m
←[H←[2J←[3J  ←[38;5;199m_←[38;5;199m_←[38;5;199m_←[38;5;199m_←[38;5;199m_←[38;5;199m ←[38;5;163m ←[38;5;164m ←[38;5;164m_←[38;5;164m_←[38;5;164m ←[38;5;164m ←[38;5;164m ←[38;5;164m ←[38;5;164m_←[38;5;164m_←[38;5;164m_←[38;5;164m_←[38;5;128m_←[38;5;129m ←[38;5;129m ←[38;5;129m ←[38;5;129m ←[38;5;129m ←[38;5;129m_←[38;5;129m_←[38;5;129m_←[38;5;129m_←[38;5;93m_←[38;5;93m_←[38;5;93m_←[38;5;93m_←[38;5;93m ←[38;5;93m ←[38;5;93m ←[38;5;93m ←[38;5;93m ←[38;5;93m ←[38;5;99m ←[38;5;63m_←[38;5;63m_←[38;5;63m_←[38;5;63m_←[38;5;63m_←[38;5;63m_←[38;5;63m_←[38;5;63m_←[38;5;63m_←[38;5;63m_←[38;5;69m_←[38;5;33m_←[38;5;33m_←[38;5;33m_
←[38;5;199m_←[38;5;199m_←[38;5;199m_←[38;5;163m ←[38;5;164m ←[38;5;164m|←[38;5;164m ←[38;5;164m/←[38;5;164m ←[38;5;164m/←[38;5;164m_←[38;5;164m_←[38;5;164m_←[38;5;164m_←[38;5;164m_←[38;5;128m_←[38;5;129m ←[38;5;129m ←[38;5;129m/←[38;5;129m_←[38;5;129m ←[38;5;129m ←[38;5;129m ←[38;5;129m ←[38;5;129m_←[38;5;93m_←[38;5;93m ←[38;5;93m ←[38;5;93m_←[38;5;93m_←[38;5;93m_←[38;5;93m/←[38;5;93m_←[38;5;93m_←[38;5;93m_←[38;5;99m_←[38;5;63m_←[38;5;63m_←[38;5;63m_←[38;5;63m_←[38;5;63m_←[38;5;63m_←[38;5;63m(←[38;5;63m_←[38;5;63m)←[38;5;63m_←[38;5;69m_←[38;5;33m_←[38;5;33m_←[38;5;33m_←[38;5;33m ←[38;5;33m ←[38;5;33m/←[38;5;33m_←[38;5;33m_←[38;5;33m_←[38;5;33m_←[38;5;39m_←[38;5;39m_←[38;5;39m_←[38;5;39m_←[38;5;39m_←[38;5;39m_←[38;5;39m_←[38;5;39m_
←[38;5;163m_←[38;5;164m_←[38;5;164m ←[38;5;164m ←[38;5;164m ←[38;5;164m|←[38;5;164m/←[38;5;164m ←[38;5;164m/←[38;5;164m_←[38;5;164m ←[38;5;164m ←[38;5;128m_←[38;5;129m ←[38;5;129m\←[38;5;129m ←[38;5;129m ←[38;5;129m_←[38;5;129m_←[38;5;129m/←[38;5;129m ←[38;5;129m ←[38;5;93m ←[38;5;93m ←[38;5;93m_←[38;5;93m_←[38;5;93m_←[38;5;93m_←[38;5;93m_←[38;5;93m ←[38;5;93m\←[38;5;93m_←[38;5;99m_←[38;5;63m_←[38;5;63m ←[38;5;63m ←[38;5;63m_←[38;5;63m_←[38;5;63m ←[38;5;63m\←[38;5;63m_←[38;5;63m ←[38;5;63m ←[38;5;69m/←[38;5;33m_←[38;5;33m ←[38;5;33m ←[38;5;33m_←[38;5;33m_←[38;5;33m ←[38;5;33m ←[38;5;33m/←[38;5;33m_←[38;5;33m ←[38;5;39m ←[38;5;39m_←[38;5;39m ←[38;5;39m\←[38;5;39m_←[38;5;39m ←[38;5;39m ←[38;5;39m_←[38;5;39m_←[38;5;38m_←[38;5;44m/
←[38;5;164m_←[38;5;164m ←[38;5;164m ←[38;5;164m/←[38;5;164m|←[38;5;164m ←[38;5;164m ←[38;5;164m/←[38;5;164m ←[38;5;128m/←[38;5;129m ←[38;5;129m ←[38;5;129m_←[38;5;129m_←[38;5;129m/←[38;5;129m ←[38;5;129m/←[38;5;129m_←[38;5;129m ←[38;5;93m ←[38;5;93m ←[38;5;93m ←[38;5;93m ←[38;5;93m ←[38;5;93m_←[38;5;93m_←[38;5;93m_←[38;5;93m_←[38;5;93m/←[38;5;99m ←[38;5;63m/←[38;5;63m_←[38;5;63m_←[38;5;63m ←[38;5;63m ←[38;5;63m/←[38;5;63m_←[38;5;63m/←[38;5;63m ←[38;5;63m/←[38;5;69m ←[38;5;33m ←[38;5;33m/←[38;5;33m ←[38;5;33m/←[38;5;33m ←[38;5;33m/←[38;5;33m_←[38;5;33m/←[38;5;33m ←[38;5;33m/←[38;5;39m ←[38;5;39m/←[38;5;39m ←[38;5;39m ←[38;5;39m_←[38;5;39m_←[38;5;39m/←[38;5;39m ←[38;5;39m ←[38;5;38m/
←[38;5;164m/←[38;5;164m_←[38;5;164m/←[38;5;164m ←[38;5;164m|←[38;5;164m_←[38;5;128m/←[38;5;129m ←[38;5;129m ←[38;5;129m\←[38;5;129m_←[38;5;129m_←[38;5;129m_←[38;5;129m/←[38;5;129m\←[38;5;129m_←[38;5;93m_←[38;5;93m/←[38;5;93m ←[38;5;93m ←[38;5;93m ←[38;5;93m ←[38;5;93m ←[38;5;93m ←[38;5;93m/←[38;5;93m_←[38;5;99m_←[38;5;63m_←[38;5;63m_←[38;5;63m/←[38;5;63m ←[38;5;63m_←[38;5;63m ←[38;5;63m ←[38;5;63m.←[38;5;63m_←[38;5;63m_←[38;5;69m_←[38;5;33m/←[38;5;33m/←[38;5;33m_←[38;5;33m/←[38;5;33m ←[38;5;33m ←[38;5;33m\←[38;5;33m_←[38;5;33m_←[38;5;33m,←[38;5;39m_←[38;5;39m/←[38;5;39m ←[38;5;39m ←[38;5;39m\←[38;5;39m_←[38;5;39m_←[38;5;39m_←[38;5;39m/←[38;5;38m/←[38;5;44m_←[38;5;44m/
←[38;5;164m ←[38;5;164m ←[38;5;164m ←[38;5;128m ←[38;5;129m ←[38;5;129m ←[38;5;129m ←[38;5;129m ←[38;5;129m ←[38;5;129m ←[38;5;129m ←[38;5;129m ←[38;5;129m ←[38;5;93m ←[38;5;93m ←[38;5;93m ←[38;5;93m ←[38;5;93m ←[38;5;93m ←[38;5;93m ←[38;5;93m ←[38;5;93m ←[38;5;93m ←[38;5;99m ←[38;5;63m ←[38;5;63m ←[38;5;63m ←[38;5;63m ←[38;5;63m ←[38;5;63m ←[38;5;63m ←[38;5;63m/←[38;5;63m_←[38;5;63m/

←[0m←[37mCreated By: ←[1m←[32mAhmed Al-Nassif←[0m
←[1m←[36mGithub: ←[37m←[4mhttps://github.com/ahmed-alnassif←[0m
←[1m←[37mE-mail: ←[35mMr.Ahmed.Nassif@gmail.com←[0m
←[1m←[34mFacebook: ←[37m←[4mhttps://fb.me/ahm3d.nassif←[0m
←[1m←[31mProgram version←[37m: ←[33m24.6.4←[0m

←[1;37m[←[32m11:25:48←[37m]←[0m←[1m←[37m[←[32mINFO←[37m]←[0m←[37m Downloading the page←[0m
←[1;37m[←[31m11:25:48←[37m]←[0m←[1m←[37m[←[31mERROR←[37m]←[0m←[37m No connection adapters were found for '[https://www.hangiev.com]'←[0m
Traceback (most recent call last):
  File "C:\Users\1TB\AppData\Local\Programs\Python\Python311\net-spider\core\request.py", line 41, in get
    return super().get(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1TB\AppData\Local\Programs\Python\Python311\venv\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1TB\AppData\Local\Programs\Python\Python311\venv\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1TB\AppData\Local\Programs\Python\Python311\venv\Lib\site-packages\requests\sessions.py", line 697, in send
    adapter = self.get_adapter(url=request.url)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1TB\AppData\Local\Programs\Python\Python311\venv\Lib\site-packages\requests\sessions.py", line 794, in get_adapter
    raise InvalidSchema(f"No connection adapters were found for {url!r}")
requests.exceptions.InvalidSchema: No connection adapters were found for '[https://www.hangiev.com]'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\1TB\AppData\Local\Programs\Python\Python311\net-spider\main.py", line 92, in <module>
    main.run(parser.spider_parser)
  File "C:\Users\1TB\AppData\Local\Programs\Python\Python311\net-spider\main.py", line 64, in run
    spider_parser(
  File "C:\Users\1TB\AppData\Local\Programs\Python\Python311\net-spider\core\parser.py", line 356, in __init__
    r=Request.get(url)
      ^^^^^^^^^^^^^^^^
  File "C:\Users\1TB\AppData\Local\Programs\Python\Python311\net-spider\core\request.py", line 43, in get
    raise ErrRequest(e)
core.request.ErrRequest: No connection adapters were found for '[https://www.hangiev.com]'

**Comment by ahmed-alnassif** [comment]
Thank you for Using the tool on Windows to solve the issue of text output. Edit the ```net-spider/core/console.py``` file, there is a snippet in the code about colors. Remove the color and make all the values ""

As for the other issue, it is not a problem but rather an incorrect use of the tool. The correct usage is:
```bash
python main.py -u https://www.hangiev.com
```

**Comment by adnanPBI** [comment]
Can I extract images(.jpg or .png), emails, structured data using your
package?
In case of image or structured data what would be expression? I need your
kind help.

**Comment by ahmed-alnassif** [comment]
For images (.jpg, .png), yes, you can extract them.
You can do that using the command:
```bash
python main -u https://example.com/page-have-images
```
After the tool is done, you can browse the site's source code and you will find the images, fonts, and the HTML, CSS, JavaScript code.

As for emails, this tool has no relation to emails, but you can use it to extract the source code of a specific front-end page and modify the code to make it an email template.

This tool has only one function: it scrapes the web page's source code.

**Comment by adnanPBI** [comment]
Source code is saved into what formats? And what is the expression to
download source code?
